# Generated by Django 4.1.6 on 2023-05-15 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
