# Generated by Django 4.1.6 on 2023-05-17 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_orderitems_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sex',
            new_name='gender',
        ),
    ]
