# Generated by Django 4.2.1 on 2023-05-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_rename_title_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sales',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
