# Generated by Django 4.2.1 on 2023-06-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_product_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('S', 'Sales'), ('M', 'Man'), ('W', 'Woman')], default='M', max_length=1),
        ),
    ]
