# Generated by Django 4.2.1 on 2023-06-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_product_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('L', 'large'), ('M', 'medium'), ('S', 'smaLL')], default='L', max_length=1),
        ),
    ]
