# Generated by Django 4.2.1 on 2023-06-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[(1, 'T-Shirt'), (2, 'Bracelet'), (3, 'Watches'), (4, 'Bags'), (5, 'Pullovers'), (6, 'Glasses'), (7, 'Perfumes'), (8, 'Pants'), (9, 'Shoes')], default=5, max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
