# Generated by Django 4.2.1 on 2023-06-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_alter_category_category_name_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[(1, 'T-Shirt'), (2, 'Bracelet'), (3, 'Watches'), (4, 'Bags'), (5, 'Pullovers'), (6, 'Glasses'), (7, 'Perfumes'), (8, 'Pants'), (9, 'Shoes')], max_length=1, null=True),
        ),
    ]
